# Generated by Django 3.0.1 on 2019-12-18 12:57

from django.db import migrations, models

from Project_Python.models import Player


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('max_number_participants', models.IntegerField( )),
                ('current_number_participants', models.IntegerField( )),
                ('start_date', models.DateField( )),
                # ('players', models.ManyToManyField('Player'))
                # ('users', models.)
            ],
        ),
    ]
