# Generated by Django 3.0 on 2019-12-31 15:44
import self as self
import users
from django.contrib.auth.models import User
from django.db import migrations, models

from Project_Python import apps
from Project_Python.models import Tournament


class Migration(migrations.Migration):

    dependencies = [
        ('Project_Python', '0001_initial'),
    ]


    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                # ('tournaments', models.ManyToManyField(to=Tournament)),
            ],
        ),
    ]
