# Generated by Django 3.0.7 on 2020-06-15 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project_Python', '0002_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='current_number_participants',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PlayerTournament',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project_Python.Player')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project_Python.Tournament')),
            ],
        ),
    ]
