# Generated by Django 3.0 on 2019-12-31 15:44
from django.contrib.auth.models import User
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('Project_Python', '0002_worker'),
    ]


    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('max_number_participants', models.IntegerField()),
                ('current_number_participants', models.IntegerField()),
                ('start_date', models.DateField()),
            ],
        ),
    ]
