# Generated by Django 3.0.7 on 2020-06-16 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project_Python', '0004_tournamentphase'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentPhasePlayer',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project_Python.Player')),
                ('tournament_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project_Python.TournamentPhase')),
            ],
        ),
    ]
